#!/bin/bash

# Define input and output files
INPUT_FILE="src/www.html"
OUTPUT_FILE="src/www.html.cpp"

# Convert the HTML file to a C++ string literal stored in PROGMEM
{
  echo '#include "www.html.hpp"'
  echo ''
  echo '// This file was generated by www-generator.sh'
  echo '// WARNING: This file is automatically generated by www-generator.sh'
  echo '// Do not edit this file manually, changes will be lost.'
  echo '// Instead, edit the original HTML file and re-run the generator.'
  echo ''
  echo 'const char htmlCode[] PROGMEM = R"rawliteral('
  cat "$INPUT_FILE"
  echo ')rawliteral";'
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE from $INPUT_FILE with PROGMEM storage."